### PR TITLE
Mreeve 461 post install

### LINKED ISSUE #443: Setup Wazuh dashboards into our kibana container to visualize wazuh agent data

### LINKED ISSUE #461: create post-install.yml to for fleet setup + installing lme/wazuh dashboards

### PR DESCRIPTION
**Pull request by mreeve-snl**
## 🗣 Description ##

This adds features to run the post install script and adds in documentation as well. 

Features/Fixes: 

-     Remove optional password setting and add in small changes to Readme.MD
-     Updates and general fixes across docs
-     creates post-install.yml: 
    1. setting up fleet
    2. fixing a few issues with wazuh (in a future release this won't be necessary)
    3. setting up custom LME dashboards
    4. setting up wazuh's dashboards
    5. setting up a read only user for analysts to connect and query LME's data
-     Fixing passwords in init-setup
-     adding starting dashboards docs + scripting
-     Remove memory limitations in kibana/elasticsearch quadlets

### 💭 Motivation and context 

closes #461 
closes #443 
We need something to run post-install steps to finalize setup of LME containers/services. 

## 🧪 Testing 

tested post-install.yml on a clean box, also the pipeline will test to see if things break

will do a test of all steps on a clean box before merge

## ✅ Pre-approval checklist ##
- [x] There is a [gitIssue](https://github.com/cisagov/LME/issues) that this PR resolves
- [x] Git Issue that this PR solves has been selected in the Development section
- [x] The PR's base branch has been modified to be the proper branch. 
- [x] Changes are limited to a single goal **AND** 
      the title reflects this in a clear human readable format
- [x] Issue that this PR solves has been selected in the Development section
- [x] I have read and agree to LME's [CONTRIBUTING.md](https://github.com/cisagov/LME/CONTRIBUTING.md) document.
- [x] The PR adheres to LME's requirements in [RELEASES.md](https://github.com/cisagov/LME/RELEASES.md#steps-to-submit-a-PR)
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.

## ✅ Pre-merge Checklist

- [x] All tests pass.
- [x] PR has been tested and the documentation for testing is above.
- [x] Squash and merge all commits into one PR level commit. 

## ✅ Post-merge Checklist

- [x] Delete the branch to keep down number of branches.
- [x] The PR is labeled with `feat` for an added new feature, `update` for an update, **OR** `fix` for a fix.
- [x] The PR contains `Resolves #<issue #>` so that merging it closes out the corresponding issue.  For example `Resolves #132`.

### CODE REVIEW

**Review by cbaxley — CHANGES_REQUESTED** [review]
We won't have them install the old dashboards. We have an importer in the upgrade steps that renames them and imports them.

**Comment by mreeve-snl** [comment]
Passed linux tests, 
running on cluster, then merging: https://github.com/cisagov/LME/actions/runs/11465538956

**Comment by mreeve-snl** [comment]
https://github.com/cisagov/LME/actions/runs/11465538956

cluster test passed

**Comment by cbaxley** [comment]
> We won't have them install the old dashboards. We have an importer in the upgrade steps that renames them and imports them.

This is fine. :)

**Review by cbaxley — APPROVED** [review]

**Comment by mreeve-snl** [comment]
testing post install on a new machine, since thats not in the tests then merging

**Comment by mreeve-snl** [comment]
OK this is good to merge whenever :) I'll merge this tomorrow if I don't see it merged then

**Pull request merged**
